os: osx
osx_image: xcode12.5
language: swift
script:
  - xcodebuild clean build test -project Factory/Factory.xcodeproj -scheme "Factory" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12" ONLY_ACTIVE_ARCH=YES
